### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sffed** [ic1414/esp_trans#1]
按里面的pcb打版，焊接好原件后，不能正常显示，使用的是devkit v1板子 ec11的编码器，ec11按网上的图添加电阻后，能旋转出一级菜单，其它字样就没有，两个0.96的屏幕显示的是同样的内容，看了下pcb板上的接口屏幕是并联的，不知道是哪出了问题

**Comment by ic1414** [comment]
不好意思我没写清楚。你需要把其中一个oled模块的iic地址改下，为此，要更改屏幕背面的一颗电阻。

**Comment by ic1414** [comment]
@sffed 不好意思我没写清楚。你需要把其中一个oled模块的iic地址改下，为此，要更改屏幕背面的一颗电阻。

**Comment by sffed** [comment]
按你的方法解决了，哈哈，另外请问下，你这个遥控和你的飞控是直接配套的么，两个开机后就能自动连接上么？连接上的话屏幕上有显示的没?

**Comment by ic1414** [comment]
@sffed 是配套的。 如果连上你就可以在屏幕上看到当前的姿态，电压之类的

**Comment by sffed** [comment]
@ic1414 谢谢，我再检查下那里出问题了
